#!/usr/bin/env bash
#
# install-toolchain.sh — installs exactly the toolchain each gate lane needs.
#
#   scripts/ci/install-toolchain.sh --profile base      # what `gate.sh fast` needs
#   scripts/ci/install-toolchain.sh --profile full      # + `gate.sh full`
#   scripts/ci/install-toolchain.sh --profile nightly   # + `gate.sh nightly`
#
# This script is the single definition of the gate's dependency set. The
# devcontainer image runs it, and every CI job runs it. That is deliberate:
# local/CI environment divergence is the most common cause of a CI failure that
# cannot be reproduced before push, and one script closes that gap permanently.
#
# See docs/decisions/0004-defensive-gate-stack.md and docs/polyglot/gate.md.
#
# Idempotent: safe to re-run. Debian/Ubuntu only — the CI runners and the
# devcontainer base image are both Ubuntu Noble.

set -euo pipefail

PROFILE=base
DRY_RUN=0

usage() {
    cat >&2 <<'EOF'
usage: scripts/ci/install-toolchain.sh [--profile base|full|nightly] [--dry-run]

  base     cmake, ninja, g++-14, shellcheck, clang-format, python3-yaml,
           yamllint, libxml2-utils, rustup toolchain (stable + clippy + rustfmt)
  full     base + clang-tidy, iwyu, sanitizer runtimes, cargo-deny
  nightly  full + valgrind, rust nightly + miri, cargo-fuzz

  --dry-run  print what would be installed and exit
EOF
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --profile) PROFILE=${2:-}; shift 2 || usage ;;
        --profile=*) PROFILE=${1#*=}; shift ;;
        --dry-run) DRY_RUN=1; shift ;;
        -h|--help) usage ;;
        *) usage ;;
    esac
done

case "$PROFILE" in
    base|full|nightly) ;;
    *) usage ;;
esac

# ── package sets ─────────────────────────────────────────────────────────────

APT_BASE=(
    build-essential
    cmake
    ninja-build
    g++-14
    shellcheck
    clang-format
    python3
    python3-yaml
    yamllint
    libxml2-utils
    git
    curl
)

APT_FULL=(
    clang
    clang-tidy
    iwyu
    libclang-rt-dev   # ASan/UBSan/TSan runtimes for clang
)

APT_NIGHTLY=(
    valgrind
)

CARGO_FULL=(cargo-deny)
CARGO_NIGHTLY=(cargo-fuzz)

packages=("${APT_BASE[@]}")
cargo_tools=()
case "$PROFILE" in
    full)
        packages+=("${APT_FULL[@]}")
        cargo_tools+=("${CARGO_FULL[@]}")
        ;;
    nightly)
        packages+=("${APT_FULL[@]}" "${APT_NIGHTLY[@]}")
        cargo_tools+=("${CARGO_FULL[@]}" "${CARGO_NIGHTLY[@]}")
        ;;
esac

if [ "$DRY_RUN" = "1" ]; then
    printf 'profile: %s\napt: %s\ncargo: %s\n' \
        "$PROFILE" "${packages[*]}" "${cargo_tools[*]:-<none>}"
    exit 0
fi

# ── apt ──────────────────────────────────────────────────────────────────────

SUDO=""
if [ "$(id -u)" -ne 0 ]; then
    SUDO="sudo"
fi

missing=()
for package in "${packages[@]}"; do
    if ! dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q '^install ok installed$'; then
        missing+=("$package")
    fi
done

if [ "${#missing[@]}" -gt 0 ]; then
    echo "installing apt packages: ${missing[*]}"
    $SUDO apt-get update -qq
    DEBIAN_FRONTEND=noninteractive $SUDO apt-get install -y -qq --no-install-recommends "${missing[@]}"
else
    echo "apt packages already present"
fi

# ── rust ─────────────────────────────────────────────────────────────────────
#
# Installed via rustup rather than apt: the gate pins clippy/rustfmt/miri
# component versions to the toolchain, and distro Rust lags too far for
# clippy::nursery to behave consistently.

if ! command -v rustup >/dev/null 2>&1; then
    echo "installing rustup"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
        | sh -s -- -y --profile minimal --default-toolchain stable
fi

# shellcheck disable=SC1091  # generated by rustup at install time
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

rustup component add clippy rustfmt >/dev/null 2>&1 || true

if [ "$PROFILE" = "nightly" ]; then
    rustup toolchain install nightly --profile minimal >/dev/null
    rustup component add --toolchain nightly miri >/dev/null 2>&1 || true
fi

for tool in "${cargo_tools[@]:-}"; do
    [ -z "$tool" ] && continue
    if command -v "$tool" >/dev/null 2>&1; then
        echo "$tool already present"
    else
        echo "installing $tool"
        cargo install --locked "$tool"
    fi
done

echo "toolchain profile '$PROFILE' ready"
