apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true

  - name: OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    jsonData:
      database: 'ems-logs-*'
      flavor: opensearch
      timeField: '@timestamp'
      pplEnabled: true
      version: '2.18.0'
    editable: true
